<a href="https://colab.research.google.com/github/AnkitSingh-12/pandas-lib/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.Series([1,2,3,'hi'])

0     1
1     2
2     3
3    hi
dtype: object

In [ ]:
l=[1,2,3,'hi']
pd.Series(l,index=['i','ii','iii','iv'])

i       1
ii      2
iii     3
iv     hi
dtype: object

In [ ]:
l=[1,2,3,'hi']
a=pd.Series(l,index=['i','ii','iii','iv'],name='values')

#accessing the element
a['i']

1

In [ ]:
l=[1,2,3,'hi']
a=pd.Series(l,index=['i','ii','iii','iv'],name='values')
print(a)

i       1
ii      2
iii     3
iv     hi
Name: values, dtype: object

In [ ]:
l=[1,2,3,'hi']
print(type(l))
a=pd.Series(l,name='values')
print(type(a))
print(a)
#accesing the  ele
a[2]

<class 'list'>
<class 'pandas.core.series.Series'>
0     1
1     2
2     3
3    hi
Name: values, dtype: object

3

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'name':['a','b','c','d'],
                 'eid':[1,2,3,4],
                 'age':[10,20,30,40]})
df

  name  eid  age
0    a    1   10
1    b    2   20
2    c    3   30
3    d    4   40

In [ ]:
import numpy as np
import pandas as pd
d=({'name':['a','b','c','d'],
                 'eid':[1,2,3,4],
                 'age':[10,20,30,40]})
df=pd.DataFrame(d)
df

  name  eid  age
0    a    1   10
1    b    2   20
2    c    3   30
3    d    4   40

In [ ]:

d={'name':['a','b','c','d'],
    'eid':[1,2,3,4],
    'age':[10,20,30,40]}
df=pd.DataFrame(d)
print(df['age'][2])


df['eid'][2]=100
df

30

<ipython-input-46-7c9b02075cdf>:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['eid'][2]=100
<ipython-input-46-7c9b02075cdf>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['eid'][2]=100

  name  eid  age
0    a    1   10
1    b    2   20
2    c  100   30
3    d    4   40

In [ ]:
d={'name':['a','b','c','d'],
    'eid':[1,2,3,4],
    'age':[10,20,30,40]}
df=pd.DataFrame(d)
print(df['age'][2])

df['d']=[1,2,3,4]
df

30

  name  eid  age  d
0    a    1   10  1
1    b    2   20  2
2    c    3   30  3
3    d    4   40  4

**read**

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv',encoding='ISO-8859-1')

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
pd.read_excel('/content/employee_satisfaction_evaluation (1).xlsx')

       EMPLOYEE #  satisfaction_level  last_evaluation
0            1003                0.38             0.53
1            1005                0.80             0.86
2            1486                0.11             0.88
3            1038                0.72             0.87
4            1057                0.37             0.52
...           ...                 ...              ...
14994       87670                0.40             0.57
14995       87673                0.37             0.48
14996       87679                0.37             0.53
14997       87681                0.11             0.96
14998       87684                0.37             0.52

[14999 rows x 3 columns]

In [ ]:
pd.read_csv('/content/drug_trial (1).csv')

           group  mean_duration
0        Control              7
1        Control              5
2        Control              4
3        Control              5
4        Control              8
..           ...            ...
75  Experimental              4
76  Experimental              3
77  Experimental              3
78  Experimental              5
79  Experimental              5

[80 rows x 2 columns]

**in built function**

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv')

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv')
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.tail(5)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

**information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

**describe**

In [ ]:
df.describe(include=object)

                    name   sex    ticket        cabin embarked
count               1309  1309      1309          295     1307
unique              1307     2       929          186        3
top     Kelly, Mr. James  male  CA. 2343  C23 C25 C27        S
freq                   2   843        11            6      914

**shape**

In [ ]:
df.shape

(1309, 11)

**column**

In [ ]:
df.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

**unique**

In [ ]:
df['age'].unique()

array([29.    ,  0.9167,  2.    , 30.    , 25.    , 48.    , 63.    ,
       39.    , 53.    , 71.    , 47.    , 18.    , 24.    , 26.    ,
       80.    ,     nan, 50.    , 32.    , 36.    , 37.    , 42.    ,
       19.    , 35.    , 28.    , 45.    , 40.    , 58.    , 22.    ,
       41.    , 44.    , 59.    , 60.    , 33.    , 17.    , 11.    ,
       14.    , 49.    , 76.    , 46.    , 27.    , 64.    , 55.    ,
       70.    , 38.    , 51.    , 31.    ,  4.    , 54.    , 23.    ,
       43.    , 52.    , 16.    , 32.5   , 21.    , 15.    , 65.    ,
       28.5   , 45.5   , 56.    , 13.    , 61.    , 34.    ,  6.    ,
       57.    , 62.    , 67.    ,  1.    , 12.    , 20.    ,  0.8333,
        8.    ,  0.6667,  7.    ,  3.    , 36.5   , 18.5   ,  5.    ,
       66.    ,  9.    ,  0.75  , 70.5   , 22.5   ,  0.3333,  0.1667,
       40.5   , 10.    , 23.5   , 34.5   , 20.5   , 30.5   , 55.5   ,
       38.5   , 14.5   , 24.5   , 60.5   , 74.    ,  0.4167, 11.5   ,
       26.5   ])

In [ ]:
df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

**value count**

In [ ]:
df['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [ ]:
d=({'a':[20,25,30,20,45,50,30],
    'b':[90,95,45,90,25,10,29],
    'c':[10,20,30,40,70,60,80]})
dummy=pd.DataFrame(d)
dummy

    a   b   c
0  20  90  10
1  25  95  20
2  30  45  30
3  20  90  40
4  45  25  70
5  50  10  60
6  30  29  80

**sort values**

In [ ]:
dummy['a'].sort_values()

0    20
3    20
1    25
2    30
6    30
4    45
5    50
Name: a, dtype: int64

**descending**

In [ ]:
dummy['a'].sort_values(ascending=False)

5    50
4    45
2    30
6    30
1    25
0    20
3    20
Name: a, dtype: int64

**slicing on dtaframe**

In [ ]:
df['name'][5:8:1]

5                  Anderson, Mr. Harry
6    Andrews, Miss. Kornelia Theodosia
7               Andrews, Mr. Thomas Jr
Name: name, dtype: object

**loc**

In [ ]:
df.loc[10:30:2,['name','age','pclass']]

                                    name   age  pclass
10                Astor, Col. John Jacob  47.0       1
12         Aubart, Mme. Leontine Pauline  24.0       1
14  Barkworth, Mr. Algernon Henry Wilson  80.0       1
16              Baxter, Mr. Quigg Edmond  24.0       1
18                 Bazzani, Miss. Albina  32.0       1
20         Beckwith, Mr. Richard Leonard  37.0       1
22                 Behr, Mr. Karl Howell  26.0       1
24                     Bird, Miss. Ellen  29.0       1
26               Bishop, Mr. Dickinson H  25.0       1
28                Bissette, Miss. Amelia  35.0       1
30          Blackwell, Mr. Stephen Weart  45.0       1

**iloc**

In [ ]:
df.iloc[10:30:2,0:5:2]

    pclass     sex  sibsp
10       1    male      1
12       1  female      0
14       1    male      0
16       1    male      0
18       1  female      0
20       1    male      1
22       1    male      0
24       1  female      0
26       1    male      1
28       1  female      0

In [ ]:
df.iloc[:6:,0:5]

,pclass,name,sex,age,sibsp
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1
5,1,"Anderson, Mr. Harry",male,48.0000,0

**rows**

In [ ]:
df.iloc[[1,19,26,31],[0,4,7]]

    pclass  sibsp      fare
1        1      1  151.5500
19       1      0   75.2417
26       1      1   91.0792
31       1      0   31.0000

**applying boolean filtering on dataframe**

In [ ]:
df['sex']=='male'

0       False
1        True
2       False
3        True
4       False
        ...
1304    False
1305    False
1306     True
1307     True
1308     True
Name: sex, Length: 1309, dtype: bool

In [ ]:
df['sex'][df['sex']=='male']

1       male
3       male
5       male
7       male
9       male
        ...
1302    male
1303    male
1306    male
1307    male
1308    male
Name: sex, Length: 843, dtype: object

In [ ]:
df[df['sex']=='male'][['name','sex']]

                                      name   sex
1           Allison, Master. Hudson Trevor  male
3     Allison, Mr. Hudson Joshua Creighton  male
5                      Anderson, Mr. Harry  male
7                   Andrews, Mr. Thomas Jr  male
9                  Artagaveytia, Mr. Ramon  male
...                                    ...   ...
1302                     Yousif, Mr. Wazli  male
1303                 Yousseff, Mr. Gerious  male
1306             Zakarian, Mr. Mapriededer  male
1307                   Zakarian, Mr. Ortin  male
1308                    Zimmerman, Mr. Leo  male

[843 rows x 2 columns]

fetch survival people titanic dataset

In [ ]:
df['name'][df['survived']==1]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
5                                   Anderson, Mr. Harry
6                     Andrews, Miss. Kornelia Theodosia
8         Appleton, Mrs. Edward Dale (Charlotte Lamson)
                             ...
1261                             Turkula, Mrs. (Hedwig)
1277                               Vartanian, Mr. David
1286    Whabee, Mrs. George Joseph (Shawneene Abi-Saab)
1290                   Wilkes, Mrs. James (Ellen Needs)
1300            Yasbeck, Mrs. Antoni (Selini Alexander)
Name: name, Length: 500, dtype: object

fetch the data  with a should me more than sixty should be survived

In [ ]:
df[(df['age']>60) & (df['survived']==1)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1
61,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,1
78,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C,1
83,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S,1
284,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,1
432,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S,1
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1

to get the data with passengers class should be three, gender should be male and survived

In [ ]:
df[(df['survived']==1)& (df['sex']=='male') & (df['pclass']==3)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
605,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0000,0,0,348122,7.6500,F G63,S,1
606,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0000,0,0,SOTON/O2 3101284,7.9250,NaN,S,1
611,3,"Aks, Master. Philip Frank",male,0.8333,0,1,392091,9.3500,NaN,S,1
613,3,"Albimona, Mr. Nassef Cassem",male,26.0000,0,0,2699,18.7875,NaN,C,1
630,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0000,0,0,350043,7.7958,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1238,3,"Tenglin, Mr. Gunnar Isidor",male,25.0000,0,0,350033,7.7958,NaN,S,1
1240,3,"Thomas, Master. Assad Alexander",male,0.4167,0,1,2625,8.5167,NaN,C,1
1254,3,"Tornquist, Mr. William Henry",male,25.0000,0,0,LINE,0.0000,NaN,S,1
1256,3,"Touma, Master. Georges Youssef",male,7.0000,1,1,2650,15.2458,NaN,C,1
1277,3,"Vartanian, Mr. David",male,22.0000,0,0,2658,7.2250,NaN,C,1